"""Add power_bonus to statuses

Revision ID: 073dad551dec
Revises: 82b6154bf630
Create Date: 2026-05-09 21:30:56.260559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073dad551dec'
down_revision: Union[str, None] = '82b6154bf630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('power_bonus', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'power_bonus')
    # ### end Alembic commands ###
