"""add is_move_stone to monster_moves and remove from moves

Revision ID: 3640b65eccfb
Revises: d51f2af4e308
Create Date: 2025-12-04 03:27:15.426226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3640b65eccfb'
down_revision: Union[str, None] = 'd51f2af4e308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_moves', sa.Column('is_move_stone', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('moves', 'is_move_stone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('is_move_stone', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('monster_moves', 'is_move_stone')
    # ### end Alembic commands ###
