"""add evolution level and condition to monsters

Revision ID: 44defde1d369
Revises: k1l2m3n4o5p6
Create Date: 2026-04-04 19:00:23.580087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44defde1d369'
down_revision: Union[str, None] = 'k1l2m3n4o5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('evolution_level', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('evolution_condition', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'evolution_condition')
    op.drop_column('monsters', 'evolution_level')
    # ### end Alembic commands ###
