"""add team_analyses table

Revision ID: 46979d812582
Revises: add_position_mm
Create Date: 2025-12-30 19:31:35.965644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46979d812582'
down_revision: Union[str, None] = 'add_position_mm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_from_cache', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'language', name='uq_team_analysis_team_language')
    )
    op.create_index('ix_team_analyses_created_at', 'team_analyses', ['created_at'], unique=False)
    op.create_index('ix_team_analyses_team_id', 'team_analyses', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_analyses_team_id', table_name='team_analyses')
    op.drop_index('ix_team_analyses_created_at', table_name='team_analyses')
    op.drop_table('team_analyses')
    # ### end Alembic commands ###
