"""add email change fields to users

Revision ID: 566038d8de60
Revises: bb370beb1e9d
Create Date: 2026-01-15 02:56:36.169187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566038d8de60'
down_revision: Union[str, None] = 'bb370beb1e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('email_change_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_change_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email_change_token'), 'users', ['email_change_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_change_token'), table_name='users')
    op.drop_column('users', 'email_change_token_expires')
    op.drop_column('users', 'email_change_token')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
