"""make_monster_trait_id_nullable

Revision ID: 5f8f2b906a70
Revises: 3640b65eccfb
Create Date: 2025-12-21 03:58:03.667116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8f2b906a70'
down_revision: Union[str, None] = '3640b65eccfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monsters', 'trait_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monsters', 'trait_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
