"""Add base_combo to moves

Revision ID: 82b6154bf630
Revises: c4cf3b18c251
Create Date: 2026-05-09 21:17:58.742212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b6154bf630'
down_revision: Union[str, None] = 'c4cf3b18c251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('base_combo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'base_combo')
    # ### end Alembic commands ###
