"""add usage and affect to statuses

Revision ID: c4cf3b18c251
Revises: 9c2e54f8a1b7
Create Date: 2026-04-15 15:11:32.585878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cf3b18c251'
down_revision: Union[str, None] = '9c2e54f8a1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_usage_enum = sa.Enum('ALL', 'ATTACK_ONLY', 'DEFENSE_ONLY', 'MOVE_SPECIFIC', name='status_usage_enum')
    status_usage_enum.create(op.get_bind(), checkfirst=True)
    status_affect_enum = sa.Enum('SELF', 'OPPONENT', name='status_affect_enum')
    status_affect_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('statuses', sa.Column('usage', status_usage_enum, nullable=False, server_default='ALL'))
    op.add_column('statuses', sa.Column('affect', status_affect_enum, nullable=False, server_default='SELF'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'affect')
    op.drop_column('statuses', 'usage')
    sa.Enum(name='status_affect_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='status_usage_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
