"""Add position column to user_monsters

Revision ID: d51f2af4e308
Revises: 12e80416704e
Create Date: 2025-11-25 23:06:54.453040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51f2af4e308'
down_revision: Union[str, None] = '12e80416704e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add position column with server_default to handle existing records
    op.add_column('user_monsters', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    # Update existing records to set position based on id order within each team
    # This SQL assigns row numbers (0-indexed) to each user_monster within its team
    op.execute("""
        UPDATE user_monsters
        SET position = subquery.row_num
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY team_id ORDER BY id) - 1 as row_num
            FROM user_monsters
        ) AS subquery
        WHERE user_monsters.id = subquery.id
    """)

    # Remove server_default after data migration
    op.alter_column('user_monsters', 'position', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_monsters', 'position')
    # ### end Alembic commands ###
